name: string.distance-pull_request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
       go-version: '1.17.6'

    - name: Install Go Packages
      run: cd algorithms && source setup.sh &&
           go get -t -v github.com/stretchr/testify/assert &&
           go get -t -v github.com/jesperancinha/string.distance/algorithms

    - name: Run Go Tests
      run: cd algorithms && source setup.sh && go test -coverprofile=../coverage.out
